'use strict'

const routesAgreement = require('./agreement')
const routesCall = require('./call')
const routesCategory = require('./category')
const routesCertificate = require('./certificate')
const routesChapter = require('./chapter')
const routesCharge = require('./charge')
const routesChat = require('./chat')
const routesClaim = require('./claim')
const routesCompany = require('./company')
const routesContact = require('./contact')
const routesCourse = require('./course')
const routesDeal = require('./deal')
const routesEmail = require('./email')
const routesEnrol = require('./enrol')
const routesLabel = require('./label')
const routesLesson = require('./lesson')
const routesLog = require('./log')
const routesMessage = require('./message')
const routesMeta = require('./meta')
const routesMigrate = require('./migration')
const routesMoodle = require('./moodle')
const routesNotification = require('./notifications')
const routesOrder = require('./order')
const routesPayment = require('./payment')
const routesProgress = require('./progress')
const routesReceipt = require('./receipt')
const routesSale = require('./sale')
const routesSend = require('./send')
const routesTemplate = require('./template')
const routesTestimony = require('./testimony')
const routesTimeline = require('./timeline')
const routesTimetable = require('./timetable')
const routesUser = require('./user')
const routesVoucher = require('./voucher')
const routesWhatsapp = require('./whatsapp')

module.exports = server => {
  server.use('/api', routesLog)
  server.use('/api', routesUser)
  server.use('/api', routesWhatsapp)
  server.use('/api', routesReceipt)
  server.use('/api', routesSale)
  server.use('/api', routesAgreement)
  server.use('/api', routesVoucher)
  server.use('/api', routesCategory)
  server.use('/api', routesCompany)
  server.use('/api', routesTemplate)
  server.use('/api', routesCall)
  server.use('/api', routesEmail)
  server.use('/api', routesProgress)
  server.use('/api', routesCourse)
  server.use('/api', routesMigrate)
  server.use('/api', routesContact)
  server.use('/api', routesNotification)
  server.use('/api', routesTimeline)
  server.use('/api', routesPayment)
  server.use('/api', routesMessage)
  server.use('/api', routesMeta)
  server.use('/api', routesMoodle)
  server.use('/api', routesLabel)
  server.use('/api', routesCertificate)
  server.use('/api', routesEnrol)
  server.use('/api', routesDeal)
  server.use('/api', routesTestimony)
  server.use('/api', routesLesson)
  server.use('/api', routesChapter)
  server.use('/api', routesChat)
  server.use('/api', routesClaim)
  server.use('/api', routesSend)
  server.use('/api', routesOrder)
  server.use('/api', routesTimetable)
  server.use('/api', routesCharge)
}
