'use strict'
const routesAgrement = require('./agreement')
const routesAuth = require('./auth')
const routesAnura = require('./anura')
const routesCallbell = require('./callbell')
const routesCategory = require('./category')
const routesCertificate = require('./certificate')
const routesCharge = require('./charge')
const routesClaim = require('./claim')
const routesContact = require('./contact')
const routesConfirmations = require('./confirmations')
const routesCourse = require('./course')
const routesDeal = require('./deal')
const routesLabel = require('./labels')
const routesLesson = require('./lesson')
const routesMain = require('./main')
const routesMeta = require('./meta')
const routesMigration = require('./migration')
const routesMoodle = require('./moodle')
const routesPaycash = require('./paycash')
const routesPayment = require('./payment')
const routesSendgrid = require('./sendgrid')
const routesTest = require('./test')
const routesTestimony = require('./testimony')
const routesUser = require('./user')
const routesWhatsapp = require('./whatsapp')
const routesZadarma = require('./zadarma')

module.exports = server => {
  server.use('/api/open', routesAgrement)
  server.use('/api/open', routesAuth)
  server.use('/api/open', routesAnura)
  server.use('/api/open', routesCallbell)
  server.use('/api/open', routesCategory)
  server.use('/api/open', routesCertificate)
  server.use('/api/open', routesCharge)
  server.use('/api/open', routesClaim)
  server.use('/api/open', routesContact)
  server.use('/api/open', routesConfirmations)
  server.use('/api/open', routesCourse)
  server.use('/api/open', routesLabel)
  server.use('/api/open', routesLesson)
  server.use('/api/open', routesMain)
  server.use('/api/open', routesMeta)
  server.use('/api/open', routesMigration)
  server.use('/api/open', routesMoodle)
  server.use('/api/open', routesPaycash)
  server.use('/api/open', routesPayment)
  server.use('/api/open', routesSendgrid)
  server.use('/api/open', routesTest)
  server.use('/api/open', routesTestimony)
  server.use('/api/open', routesUser)
  server.use('/api/open', routesWhatsapp)
  server.use('/api/open', routesZadarma)
  server.use('/api/open', routesDeal)
}
